[project]
name = "f"
version = "0.0.0"
description = "f-utils/f lib. Allow constructive type safety through a functional approach."
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "python-lsp-server>=1.12.0",
]
